version: '3'

services:
  minio:
    image: quay.io/minio/minio
    hostname: minio
    ports:
      - 9001:9000
      - 9090:9090
    env_file:
      - .env
    volumes:
      - ./data:/mnt/data
    command:
      minio server --console-address ":9090"

volumes:
  data:
